//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBaseDatos
{
    using System;
    
    public partial class Seleccionar_GridFactura_Result1
    {
        public string IntFactura_Horom { get; set; }
        public string DtmFecha_Horom { get; set; }
        public Nullable<decimal> IntHoroIni_Horom { get; set; }
        public Nullable<decimal> IntHoroFin_Horom { get; set; }
        public Nullable<decimal> IntHorasOrdina_Horom { get; set; }
        public decimal IntStandBy_Horom { get; set; }
        public Nullable<decimal> IntHoroIniExt_Horom { get; set; }
        public Nullable<decimal> IntHoroFinExt_Horom { get; set; }
        public Nullable<decimal> IntHoraIniExt_Horom { get; set; }
        public Nullable<decimal> IntHoraFinExt_Horom { get; set; }
        public Nullable<decimal> IntHorasExtras_Horom { get; set; }
        public Nullable<decimal> IntHorasCobrar_Horom { get; set; }
        public Nullable<decimal> DblTransporte_Horom { get; set; }
        public decimal DblValorHora_Horom { get; set; }
        public Nullable<decimal> Total_Horas { get; set; }
        public Nullable<decimal> Valor { get; set; }
    }
}
