//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMaquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMaquina()
        {
            this.TblHorometro = new HashSet<TblHorometro>();
        }
    
        public int IntCodigo_Maquina { get; set; }
        public string StrNombre_Maquina { get; set; }
        public string StrModelo_Maquina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHorometro> TblHorometro { get; set; }
    }
}
