<%@ Page Title="" Language="C#" MasterPageFile="~/HSExcavaciones.Master" AutoEventWireup="true" CodeBehind="Clientes.aspx.cs" Inherits="HSExcavacionesWeb.Clientes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <link rel="stylesheet" href="css/Style.css" />
    <aside>
        <section class="section-dropdown" >
            <div>
                <h2>CREACION CLIENTES Y OBRAS
                </h2>
            </div>
            <div >
                <div class="cliente-obra">
                    <div>Cliente:</div>
                    <div>
                        <asp:DropDownList ID="dpConsultaCliente" runat="server" CssClass="form-control" Width="300px" Height="30px" DataSourceID="SqlCliente" DataTextField="StrNombre_Cliente" DataValueField="StrDocumento_Cliente" AutoPostBack="True" OnSelectedIndexChanged="dpConsultaCliente_SelectedIndexChanged"></asp:DropDownList>
                        <asp:SqlDataSource ID="SqlCliente" runat="server" ConnectionString="<%$ ConnectionStrings:DBHSExcavcionesConnectionString %>" SelectCommand="SELECT [StrDocumento_Cliente], [StrNombre_Cliente] FROM [TblCliente] order by  [StrNombre_Cliente] asc"></asp:SqlDataSource>
                    </div>
                    <div>
                        <asp:LinkButton ID="lnkNuevo" runat="server" Text="Nuevo" Width="100px" OnClick="lnkNuevo_Click"></asp:LinkButton>
                    </div>
                </div>
                <div class="cliente-obra">
                    <div>Documento Cliente:</div>
                    <div>
                        <asp:TextBox ID="txtDocCliente" runat="server" CssClass="form-control" Width="300px" Height="30px" MaxLength="50"></asp:TextBox>
                    </div>
                    
                </div>
                <div class="cliente-obra">
                    <div>Nombre Cliente:</div>
                    <div>
                        <asp:TextBox ID="txtNombreCliente" runat="server" CssClass="form-control" Width="300px" Height="30px" MaxLength="90"></asp:TextBox>
                    </div>
                </div>
                <div class="cliente-obra">
                    <div>Nombre Obra:</div>
                    <div>
                        <asp:TextBox ID="txtObra" runat="server" CssClass="form-control" Width="300px" Height="30px" MaxLength="150"></asp:TextBox>
                    </div>
                    <div>
                        <asp:LinkButton ID="lnkAgregarOb" runat="server"  Text="Agregar Obra" Width="100px" OnClick="lnkAgregarOb_Click"></asp:LinkButton>
                    </div>
                   
                </div>
                <div class="cliente-obra">
                    <h5>
                        <asp:Label ID="lblObrasNuevas" runat="server" Text="Obras Nuevas" Visible="False"></asp:Label>
                    </h5>
                    <div>
                        <asp:GridView ID="grdClientes" runat="server" AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnRowDeleting="grdClientes_RowDeleting">
                            <AlternatingRowStyle BackColor="White" />
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                        <br />
                         <h5>
                        <asp:Label ID="lblObrasActuales" runat="server" Text="Obras Actuales" Visible="False"></asp:Label>
                        </h5>
                        <br />
                        <asp:GridView ID="grdConsultaObras" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Intcodigo_Obra" DataSourceID="SqlConsultarObras" ForeColor="Black" GridLines="Vertical">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:CommandField ShowEditButton="True" />
                                <asp:BoundField DataField="Intcodigo_Obra" HeaderText="Intcodigo_Obra" InsertVisible="False" ReadOnly="True" SortExpression="Intcodigo_Obra" Visible="False" />
                                <asp:BoundField DataField="StrNombre_Obra" HeaderText="Nombre Obra" SortExpression="StrNombre_Obra" />
                            </Columns>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="SqlConsultarObras" runat="server" ConnectionString="<%$ ConnectionStrings:DBHSExcavcionesConnectionString %>" SelectCommand="Seleccionar_Obras" SelectCommandType="StoredProcedure" UpdateCommand="Actualizar_Obras" UpdateCommandType="StoredProcedure">
                            <SelectParameters>
                                <asp:ControlParameter ControlID="dpConsultaCliente" Name="StrDocumento_Cliente" PropertyName="SelectedValue" Type="String" />
                            </SelectParameters>
                            <UpdateParameters>
                                <asp:ControlParameter ControlID="grdConsultaObras" Name="Intcodigo_Obra" PropertyName="SelectedValue" Type="Int32" />
                                <asp:ControlParameter ControlID="grdConsultaObras" Name="StrNombre_Obra" PropertyName="SelectedValue" Type="String" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                        <br />
                    </div>
                 <div>
                       <asp:LinkButton ID="lnkGuardar" runat="server"  Text="Guardar" Width="100px" OnClick="lnkGuardar_Click" Visible ="false"></asp:LinkButton>
                 </div>
                </div>
              
                <div class="cliente-obra">
                    <asp:Label ID="lblError" runat="server"></asp:Label> 
                </div>
            </div>
        </section>
    </aside>
</asp:Content>
